### PR TITLE
Harden against bad input. Fixes #23

### LINKED ISSUE #23: Lots of crashes when running `cat /dev/random`
There are a few places in the code that can crash when bad input is received from `cat /dev/random`

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

File: XtermSharp/InputHandler.cs [hunk 1]
```diff
@@ -1437,9 +1437,10 @@ void LinePosAbsolute (int [] pars)
 			var p = Math.Max (pars.Length == 0 ? 1 : pars [0], 1);
 			var buffer = terminal.Buffer;
 
-			buffer.Y = p - 1;
-			if (buffer.Y >= terminal.Rows)
+			if (p - 1 >= terminal.Rows)
 				buffer.Y = terminal.Rows - 1;
+			else
+				buffer.Y = p - 1;
 		}
```
Comment (migueldeicaza) [inline XtermSharp/InputHandler.cs]: This change looks like a no-op, I do not understand what changes.

File: XtermSharp/Pty.cs [hunk 2]
```diff
@@ -21,7 +21,7 @@ public class Pty {
 		[DllImport ("/cvs/XtermSharp/helper/libpty.dylib", EntryPoint ="fork_and_exec")]
 		extern static int HeavyFork (string process, string [] args, string [] env, out int master, UnixWindowSize winSize);
 
-		static bool HeavyDuty = true;
+		static bool HeavyDuty = false;
```
Comment (migueldeicaza) [inline XtermSharp/Pty.cs]: I dont think we want this, what is the reason for this change?

The reason for the library is that otherwise, this breaks on Catalina.

File: XtermSharp/InputHandler.cs (hunk 1 above)
Comment (migueldeicaza) [reply XtermSharp/InputHandler.cs]: Oh, I see, because buffer.Y is doing validation.
